### ISSUE TITLE
Startup Crash - NullPointer in Loading and Saving Config

### ISSUE THREAD

**Issue by justwheel** [CrystalCraftMC/CrystalSpace#1]
Whenever the plugin is first started, a NullPointerException is thrown in regards to loading and saving the configuration. This likely involves the variables which were commented out.

```
[11:35:48 INFO]: [CrystalSpace] Loading CrystalSpace vv3.0.0-ALPHA1
[11:35:48 INFO]: [CrystalSpace] Enabling CrystalSpace vv3.0.0-ALPHA1
[11:35:48 ERROR]: Error occurred while enabling CrystalSpace vv3.0.0-ALPHA1 (Is it up to date?)
java.lang.NullPointerException
    at com.crystalcraftmc.crystalspace.config.SpaceConfig.loadConfig(SpaceConfig.java:88) ~[?:?]
    at com.crystalcraftmc.crystalspace.config.SpaceConfig.getConfig(SpaceConfig.java:44) ~[?:?]
    at com.crystalcraftmc.crystalspace.api.SpaceConfigHandler.getDebugging(SpaceConfigHandler.java:51) ~[?:?]
    at com.crystalcraftmc.crystalspace.handlers.MessageHandler.debugPrint(MessageHandler.java:37) ~[?:?]
    at com.crystalcraftmc.crystalspace.Space.onEnable(Space.java:73) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:153) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by justwheel** [comment]
Also seems to happen on server stop?

```
[11:39:10 INFO]: [CrystalSpace] Disabling CrystalSpace vv3.0.0-ALPHA1
[11:39:10 ERROR]: Error occurred while disabling CrystalSpace vv3.0.0-ALPHA1 (Is it up to date?)
java.lang.NullPointerException
    at com.crystalcraftmc.crystalspace.config.SpaceConfig.loadConfig(SpaceConfig.java:88) ~[?:?]
    at com.crystalcraftmc.crystalspace.config.SpaceConfig.getConfig(SpaceConfig.java:44) ~[?:?]
    at com.crystalcraftmc.crystalspace.api.SpaceLangHandler.getDisabledMessage(SpaceLangHandler.java:34) ~[?:?]
    at com.crystalcraftmc.crystalspace.Space.onDisable(Space.java:63) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:334) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:430) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:561) [spigot.jar:git-Spigot-b1e6da1-1092acb]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

**Comment by justwheel** [comment]
It appears that this issue was from lack of changing names from "bSpace" to "CrystalSpace". Watch your p's and q's.
