### ISSUE TITLE
spaceWorldNames ArrayList is not filled with list of space worlds

### ISSUE THREAD

**Issue by justwheel** [CrystalCraftMC/CrystalSpace#6]
This issue comes from this error:

```
[09:09:52 INFO]: CrystalCraftMC issued server command: /space list
[09:09:52 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'space' in plugin CrystalSpace v3.0.0-ALPHA4
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
    at com.crystalcraftmc.crystalspace.commands.SpaceListCommand.command(SpaceListCommand.java:52) ~[?:?]
    at com.crystalcraftmc.crystalspace.commands.SpaceCommand.<init>(SpaceCommand.java:33) ~[?:?]
    at com.crystalcraftmc.crystalspace.commands.SpaceListCommand.<init>(SpaceListCommand.java:33) ~[?:?]
    at com.crystalcraftmc.crystalspace.commands.SpaceCommandHandler.onCommand(SpaceCommandHandler.java:74) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
    ... 14 more
```

Upon further inspection, it seems that the `spaceWorldNames` ArrayList found [here](https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/java/com/crystalcraftmc/crystalspace/api/SpaceWorldHandler.java#L29) is not being initialized like it should. The corresponding lines that relate to this particular ArrayList are lines [39](https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/java/com/crystalcraftmc/crystalspace/api/SpaceWorldHandler.java#L39) and [68-64](https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/java/com/crystalcraftmc/crystalspace/api/SpaceWorldHandler.java#L68-L74) in the `SpaceWorldHandler` class, found in the API.

Because this ArrayList is empty, it is throwing a NPE when used in the `SpaceListCommand` class.

Goal: Evaluate [this method](https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/java/com/crystalcraftmc/crystalspace/api/SpaceWorldHandler.java#L36-L42) to figure out what's going on.

_Related_: [Stacktrace from iffa](http://pastebin.com/jcYCgKd2)

**Comment by immaterial-ctrl** [comment]
I looked at it, and the only thing I can think of is that there might be a method that would add to the arraylist somewhere, that is what I am looking for now...

So in lines 159 to 172 is the method to add worlds via String, now to find the command that calls this method, and perhaps we can add it, so that when we use /space list there is already worlds on the list. (I am guessing it would be super bad to code a fake world in for testing purposes? Or even code in a minor edit, that has getServer().getWorld().getWorldName() and use that to add in for us, just so we can see if it works...)

**Comment by Jacc734** [comment]
So in lines 159 to 172 is the method to add worlds via String, now to find the command that calls this method, and perhaps we can add it, so that when we use /space list there is already worlds on the list. (I am guessing it would be super bad to code a fake world in for testing purposes?)

**Comment by iffa** [comment]
I believe this issue is fixed in my latest commit, at least when I was testing it. Soneone test it and close the issue after it's confirmed working?

**Comment by immaterial-ctrl** [comment]
Worked like a charm: Output ingame "No space worlds are loaded! :(" (cause I didnt have any)
Console had no issues with it.

**Comment by iffa** [comment]
Alright... closing this issue, if it ever pops up again, we'll make a new issue with new details :dash:
